language: cpp

dist: trusty

os:
- linux

services:
- docker

before_install:
- docker pull dealii/dealii


script:
    - echo "Docker has been pulled"
    ############################################################################
    # Build 
    ############################################################################

    # Download and compile p4est
     #- mkdir p4est
     #- cd p4est
     #- wget https://www.dealii.org/9.0.0/external-libs/p4est-setup.sh
     #- bash p4est-setup.sh
     #- cd ..
     #- mkdir -p dealii
     #- cd dealii
     #- git clone https://github.com/dealii/dealii.git
     #- mkdir -p build
     #- cd build
     #- cmake -DDEAL_II_WITH_MPI=ON -DDEAL_II_COMPILE_EXAMPLES=OFF ../dealii
     #- #make -j4
